from __future__ import annotations

from collections.abc import Iterable
import math

import numpy as np
import trimesh
from shapely import constrained_delaunay_triangles
from shapely.geometry import MultiPolygon, Polygon, box
from shapely.geometry.polygon import orient


def rounded_rectangle(width: float, height: float, radius: float, *, cx: float = 0.0, cy: float = 0.0, resolution: int = 8) -> Polygon:
    radius = max(0.0, min(radius, width / 2.0 - 1e-6, height / 2.0 - 1e-6))
    if radius <= 1e-6:
        return box(cx - width / 2, cy - height / 2, cx + width / 2, cy + height / 2)
    core = box(
        cx - width / 2 + radius,
        cy - height / 2 + radius,
        cx + width / 2 - radius,
        cy + height / 2 - radius,
    )
    return core.buffer(radius, quad_segs=resolution, join_style=1)


def _polygons(geometry) -> list[Polygon]:
    if geometry.is_empty:
        return []
    if isinstance(geometry, Polygon):
        return [geometry]
    if isinstance(geometry, MultiPolygon):
        return list(geometry.geoms)
    return [g for g in getattr(geometry, "geoms", []) if isinstance(g, Polygon)]


def _finalize_constructed_mesh(vertices, faces) -> trimesh.Trimesh:
    """Clean a mesh without invoking trimesh's optional SciPy paths.

    The vertices/faces passed here are generated by this application with known
    winding.  Trimesh ``process(validate=True)`` calls ``body_count`` while
    fixing normals, which requires SciPy in recent trimesh versions.  SciPy is
    intentionally not a standard dependency of this lightweight application.
    """
    mesh = trimesh.Trimesh(
        vertices=np.asarray(vertices, dtype=float),
        faces=np.asarray(faces, dtype=np.int64),
        process=False,
        validate=False,
    )
    if mesh.is_empty:
        return mesh

    mesh.remove_infinite_values()
    mesh.merge_vertices()
    keep = mesh.unique_faces() & mesh.nondegenerate_faces()
    if not bool(np.all(keep)):
        mesh.update_faces(keep)
    mesh.remove_unreferenced_vertices()

    # Each primitive produced here is a single closed solid.  Correct a global
    # inversion directly; do not ask trimesh to discover multiple bodies.
    if mesh.is_watertight and float(mesh.volume) < 0.0:
        mesh.invert()
    return mesh


def face_component_count(mesh: trimesh.Trimesh) -> int:
    """Count edge-connected face components using a small union-find.

    This replaces ``mesh.body_count`` so generation and validation work on a
    standard install without SciPy.
    """
    face_count = len(mesh.faces)
    if face_count == 0:
        return 0

    parent = list(range(face_count))
    rank = [0] * face_count

    def find(item: int) -> int:
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra == rb:
            return
        if rank[ra] < rank[rb]:
            parent[ra] = rb
        elif rank[ra] > rank[rb]:
            parent[rb] = ra
        else:
            parent[rb] = ra
            rank[ra] += 1

    edge_owner: dict[tuple[int, int], int] = {}
    for face_index, face in enumerate(np.asarray(mesh.faces, dtype=np.int64)):
        for a, b in ((int(face[0]), int(face[1])), (int(face[1]), int(face[2])), (int(face[2]), int(face[0]))):
            edge = (a, b) if a < b else (b, a)
            previous = edge_owner.get(edge)
            if previous is None:
                edge_owner[edge] = face_index
            else:
                union(face_index, previous)

    return len({find(i) for i in range(face_count)})


def extrude_geometry(geometry, z0: float, z1: float) -> list[trimesh.Trimesh]:
    return [extrude_polygon(poly, z0, z1) for poly in _polygons(geometry) if poly.area > 1e-7]


def extrude_polygon(poly: Polygon, z0: float, z1: float) -> trimesh.Trimesh:
    if z1 <= z0:
        raise ValueError("z1 must be greater than z0")
    poly = orient(poly, sign=1.0)
    vertices: list[tuple[float, float, float]] = []
    faces: list[tuple[int, int, int]] = []
    index: dict[tuple[int, int, int], int] = {}

    def vid(x: float, y: float, z: float) -> int:
        key = (round(x * 1_000_000), round(y * 1_000_000), round(z * 1_000_000))
        if key not in index:
            index[key] = len(vertices)
            vertices.append((x, y, z))
        return index[key]

    for tri in constrained_delaunay_triangles(poly).geoms:
        rp = tri.representative_point()
        if not poly.covers(rp):
            continue
        coords = list(tri.exterior.coords)[:3]
        signed = sum(
            coords[i][0] * coords[(i + 1) % 3][1] - coords[(i + 1) % 3][0] * coords[i][1]
            for i in range(3)
        )
        if signed < 0:
            coords.reverse()
        top = [vid(x, y, z1) for x, y in coords]
        bottom = [vid(x, y, z0) for x, y in coords]
        faces.append(tuple(top))
        faces.append((bottom[2], bottom[1], bottom[0]))

    rings = [poly.exterior, *poly.interiors]
    for ring in rings:
        coords = list(ring.coords)
        for a, b in zip(coords[:-1], coords[1:]):
            a0 = vid(a[0], a[1], z0)
            b0 = vid(b[0], b[1], z0)
            a1 = vid(a[0], a[1], z1)
            b1 = vid(b[0], b[1], z1)
            faces.append((a0, b0, b1))
            faces.append((a0, b1, a1))

    return _finalize_constructed_mesh(vertices, faces)


def rounded_rect_perimeter(width: float, height: float, radius: float, segments_per_corner: int = 8) -> np.ndarray:
    radius = max(0.0, min(radius, width / 2 - 1e-6, height / 2 - 1e-6))
    if radius <= 1e-6:
        return np.array([
            [width / 2, height / 2],
            [-width / 2, height / 2],
            [-width / 2, -height / 2],
            [width / 2, -height / 2],
        ], dtype=float)

    pts: list[tuple[float, float]] = []
    centers = [
        (width / 2 - radius, height / 2 - radius, 0, 90),
        (-width / 2 + radius, height / 2 - radius, 90, 180),
        (-width / 2 + radius, -height / 2 + radius, 180, 270),
        (width / 2 - radius, -height / 2 + radius, 270, 360),
    ]
    for cx, cy, a0, a1 in centers:
        for angle in np.linspace(a0, a1, segments_per_corner, endpoint=False):
            rad = math.radians(angle)
            pts.append((cx + radius * math.cos(rad), cy + radius * math.sin(rad)))
    return np.asarray(pts, dtype=float)


def loft_rounded_rect(levels: Iterable[tuple[float, float, float, float]], *, cx: float = 0.0, cy: float = 0.0) -> trimesh.Trimesh:
    lv = list(levels)
    if len(lv) < 2:
        raise ValueError("At least two loft levels are required")
    loops = [rounded_rect_perimeter(w, h, r) + np.array([cx, cy]) for z, w, h, r in lv]
    n = len(loops[0])
    if any(len(loop) != n for loop in loops):
        raise ValueError("Loft loops must have the same vertex count")

    vertices: list[list[float]] = []
    for (z, _, _, _), loop in zip(lv, loops):
        vertices.extend([[x, y, z] for x, y in loop])

    faces: list[tuple[int, int, int]] = []
    for layer in range(len(lv) - 1):
        low = layer * n
        high = (layer + 1) * n
        for i in range(n):
            j = (i + 1) % n
            faces.append((low + i, low + j, high + j))
            faces.append((low + i, high + j, high + i))

    bottom_center = len(vertices)
    vertices.append([cx, cy, lv[0][0]])
    top_center = len(vertices)
    vertices.append([cx, cy, lv[-1][0]])
    for i in range(n):
        j = (i + 1) % n
        faces.append((bottom_center, j, i))
        top_base = (len(lv) - 1) * n
        faces.append((top_center, top_base + i, top_base + j))

    return _finalize_constructed_mesh(vertices, faces)



def loft_rounded_ring(
    levels: Iterable[tuple[float, float, float, float, float, float, float, float]],
    *,
    cx: float = 0.0,
    cy: float = 0.0,
) -> trimesh.Trimesh:
    """Loft a closed rounded-rectangle ring through multiple Z levels.

    Every level is ``(z, outer_w, outer_h, outer_r, inner_w, inner_h,
    inner_r_x, inner_r_y)``.  The final two radius values are kept separate so
    clipped/partial cells can retain sensible rounding in each direction.  The
    current generator passes the same value for both axes; accepting both here
    avoids baking that limitation into the mesh format.

    The outer and inner loops use the same sample count and angular positions,
    so the side walls and annular caps can be joined without a triangulation
    dependency.
    """
    lv = list(levels)
    if len(lv) < 2:
        raise ValueError("At least two ring loft levels are required")

    outer_loops: list[np.ndarray] = []
    inner_loops: list[np.ndarray] = []
    for z, ow, oh, outer_r, iw, ih, inner_rx, inner_ry in lv:
        if iw <= 0.05 or ih <= 0.05:
            raise ValueError("Ring opening is too small")
        # rounded_rect_perimeter is circular at corners.  Use the smaller of
        # the requested X/Y radii; partial cells still receive a valid contour.
        ir = min(inner_rx, inner_ry)
        outer_loops.append(rounded_rect_perimeter(ow, oh, outer_r) + np.array([cx, cy]))
        inner_loops.append(rounded_rect_perimeter(iw, ih, ir) + np.array([cx, cy]))

    n = len(outer_loops[0])
    if any(len(loop) != n for loop in outer_loops + inner_loops):
        raise ValueError("Ring loft loops must have the same vertex count")

    vertices: list[list[float]] = []
    for (z, *_), outer, inner in zip(lv, outer_loops, inner_loops):
        vertices.extend([[x, y, z] for x, y in outer])
        vertices.extend([[x, y, z] for x, y in inner])

    faces: list[tuple[int, int, int]] = []
    stride = n * 2

    # Sloped/vertical outer and inner walls.
    for layer in range(len(lv) - 1):
        low = layer * stride
        high = (layer + 1) * stride
        low_inner = low + n
        high_inner = high + n
        for i in range(n):
            j = (i + 1) % n
            # Outer wall, outward normal.
            faces.append((low + i, low + j, high + j))
            faces.append((low + i, high + j, high + i))
            # Inner wall, normal toward the opening.
            faces.append((low_inner + i, high_inner + j, low_inner + j))
            faces.append((low_inner + i, high_inner + i, high_inner + j))

    # Bottom and top annular caps.
    bottom_outer = 0
    bottom_inner = n
    top_outer = (len(lv) - 1) * stride
    top_inner = top_outer + n
    for i in range(n):
        j = (i + 1) % n
        # Bottom faces point down.
        faces.append((bottom_outer + i, bottom_inner + j, bottom_outer + j))
        faces.append((bottom_outer + i, bottom_inner + i, bottom_inner + j))
        # Top faces point up.
        faces.append((top_outer + i, top_outer + j, top_inner + j))
        faces.append((top_outer + i, top_inner + j, top_inner + i))

    return _finalize_constructed_mesh(vertices, faces)

def concatenate(meshes: Iterable[trimesh.Trimesh]) -> trimesh.Trimesh:
    valid = [m for m in meshes if m is not None and len(m.faces) > 0]
    if not valid:
        raise ValueError("生成対象のメッシュがありません。")
    result = trimesh.util.concatenate(valid)
    result.remove_infinite_values()
    result.remove_unreferenced_vertices()
    # The component primitives are already outward-facing.  Avoid
    # fix_normals(multibody=True), which pulls in optional SciPy routines.
    return result
